# Site settings
title: 海怪的blog.
motto: do it.
email: near0608@163.com
description: blog
baseurl: ""
url: "near68.github.io" 
twitter_username: #
github_username: #

# Build settings
markdown: kramdown
